// ------------------------------------------------------------------------------
// <auto-generated>
// Этот код создан программой.
// Исполняемая версия:4.0.30319.42000
// 
// Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
// повторной генерации кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic; // Install-Package Microsoft.VisualBasic

namespace My.Resources
{

    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    /// <summary>
    /// Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    [HideModuleName()]
    internal static partial class Resources
    {
        private static System.Resources.ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        /// <summary>
        /// Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("Minecraft2D.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Перезаписывает свойство CurrentUICulture текущего потока для всех
        /// обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bedrock
        {
            get
            {
                var obj = ResourceManager.GetObject("bedrock", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coal
        {
            get
            {
                var obj = ResourceManager.GetObject("coal", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coal_ore
        {
            get
            {
                var obj = ResourceManager.GetObject("coal_ore", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COBBLESTONE
        {
            get
            {
                var obj = ResourceManager.GetObject("COBBLESTONE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cobblestone4
        {
            get
            {
                var obj = ResourceManager.GetObject("cobblestone4", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND_AXE
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND_AXE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND_AXE_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND_AXE_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_block
        {
            get
            {
                var obj = ResourceManager.GetObject("diamond_block", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diamond_ore
        {
            get
            {
                var obj = ResourceManager.GetObject("diamond_ore", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND_PICKAXE
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND_PICKAXE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND_PICKAXE_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND_PICKAXE_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND_SHOVEL
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND_SHOVEL", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND_SHOVEL_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND_SHOVEL_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND_SWORD
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND_SWORD", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIAMOND_SWORD_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("DIAMOND_SWORD_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DIRT
        {
            get
            {
                var obj = ResourceManager.GetObject("DIRT", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt1
        {
            get
            {
                var obj = ResourceManager.GetObject("dirt1", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap furnace_front_off
        {
            get
            {
                var obj = ResourceManager.GetObject("furnace_front_off", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap furnace_front_on
        {
            get
            {
                var obj = ResourceManager.GetObject("furnace_front_on", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap glass
        {
            get
            {
                var obj = ResourceManager.GetObject("glass", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GLASSBLOCK
        {
            get
            {
                var obj = ResourceManager.GetObject("GLASSBLOCK", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GOLD
        {
            get
            {
                var obj = ResourceManager.GetObject("GOLD", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_block
        {
            get
            {
                var obj = ResourceManager.GetObject("gold_block", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_ore
        {
            get
            {
                var obj = ResourceManager.GetObject("gold_ore", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grass_side
        {
            get
            {
                var obj = ResourceManager.GetObject("grass_side", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid_Sapling
        {
            get
            {
                var obj = ResourceManager.GetObject("Grid_Sapling", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_AXE
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON_AXE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_AXE_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON_AXE_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iron_block
        {
            get
            {
                var obj = ResourceManager.GetObject("iron_block", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iron_ore
        {
            get
            {
                var obj = ResourceManager.GetObject("iron_ore", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_PICKAXE
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON_PICKAXE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_PICKAXE_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON_PICKAXE_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_SHOVEL
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON_SHOVEL", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_SHOVEL_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON_SHOVEL_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_SWORD
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON_SWORD", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_SWORD_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("IRON_SWORD_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leaves
        {
            get
            {
                var obj = ResourceManager.GetObject("leaves", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap log_oak
        {
            get
            {
                var obj = ResourceManager.GetObject("log_oak", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NCLogo
        {
            get
            {
                var obj = ResourceManager.GetObject("NCLogo", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap netcraft
        {
            get
            {
                var obj = ResourceManager.GetObject("netcraft", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OBSIDIAN
        {
            get
            {
                var obj = ResourceManager.GetObject("OBSIDIAN", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obsidian1
        {
            get
            {
                var obj = ResourceManager.GetObject("obsidian1", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap planks_oak
        {
            get
            {
                var obj = ResourceManager.GetObject("planks_oak", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap platformPack_tile001
        {
            get
            {
                var obj = ResourceManager.GetObject("platformPack_tile001", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap platformPack_tile004
        {
            get
            {
                var obj = ResourceManager.GetObject("platformPack_tile004", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap platformPack_tile016
        {
            get
            {
                var obj = ResourceManager.GetObject("platformPack_tile016", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap platformPack_tile034
        {
            get
            {
                var obj = ResourceManager.GetObject("platformPack_tile034", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player1Texture
        {
            get
            {
                var obj = ResourceManager.GetObject("Player1Texture", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2Texture
        {
            get
            {
                var obj = ResourceManager.GetObject("Player2Texture", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sand
        {
            get
            {
                var obj = ResourceManager.GetObject("sand", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SANDBLOCK
        {
            get
            {
                var obj = ResourceManager.GetObject("SANDBLOCK", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sprite
        {
            get
            {
                var obj = ResourceManager.GetObject("sprite", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STICK
        {
            get
            {
                var obj = ResourceManager.GetObject("STICK", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_AXE
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE_AXE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_AXE_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE_AXE_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_PICKAXE
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE_PICKAXE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_PICKAXE_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE_PICKAXE_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_SHOVEL
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE_SHOVEL", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_SHOVEL_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE_SHOVEL_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_SWORD
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE_SWORD", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_SWORD_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("STONE_SWORD_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stone1
        {
            get
            {
                var obj = ResourceManager.GetObject("stone1", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vbnet_edition
        {
            get
            {
                var obj = ResourceManager.GetObject("vbnet_edition", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap water_still
        {
            get
            {
                var obj = ResourceManager.GetObject("water_still", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOOD
        {
            get
            {
                var obj = ResourceManager.GetObject("WOOD", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOODEN_AXE
        {
            get
            {
                var obj = ResourceManager.GetObject("WOODEN_AXE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOODEN_AXE_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("WOODEN_AXE_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOODEN_PICKAXE
        {
            get
            {
                var obj = ResourceManager.GetObject("WOODEN_PICKAXE", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOODEN_PICKAXE_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("WOODEN_PICKAXE_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOODEN_SHOVEL
        {
            get
            {
                var obj = ResourceManager.GetObject("WOODEN_SHOVEL", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOODEN_SHOVEL_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("WOODEN_SHOVEL_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOODEN_SWORD
        {
            get
            {
                var obj = ResourceManager.GetObject("WOODEN_SWORD", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WOODEN_SWORD_FLIPPED
        {
            get
            {
                var obj = ResourceManager.GetObject("WOODEN_SWORD_FLIPPED", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }
    }
}