'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Minecraft2D.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bedrock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bedrock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coal_ore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coal_ore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COBBLESTONE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COBBLESTONE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cobblestone4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cobblestone4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND_AXE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND_AXE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND_AXE_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND_AXE_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diamond_block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamond_block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diamond_ore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamond_ore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND_PICKAXE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND_PICKAXE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND_PICKAXE_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND_PICKAXE_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND_SHOVEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND_SHOVEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND_SHOVEL_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND_SHOVEL_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND_SWORD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND_SWORD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIAMOND_SWORD_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIAMOND_SWORD_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DIRT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIRT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirt1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirt1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property furnace_front_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("furnace_front_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property furnace_front_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("furnace_front_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property glass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("glass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GLASSBLOCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GLASSBLOCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GOLD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GOLD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gold_block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gold_block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gold_ore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gold_ore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass_side() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass_side", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grid_Sapling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grid_Sapling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON_AXE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON_AXE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON_AXE_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON_AXE_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iron_block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iron_block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iron_ore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iron_ore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON_PICKAXE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON_PICKAXE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON_PICKAXE_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON_PICKAXE_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON_SHOVEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON_SHOVEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON_SHOVEL_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON_SHOVEL_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON_SWORD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON_SWORD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IRON_SWORD_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IRON_SWORD_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property leaves() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leaves", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property log_oak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log_oak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NCLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NCLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property netcraft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netcraft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBSIDIAN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBSIDIAN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property obsidian1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("obsidian1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property planks_oak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("planks_oak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property platformPack_tile001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("platformPack_tile001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property platformPack_tile004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("platformPack_tile004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property platformPack_tile016() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("platformPack_tile016", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property platformPack_tile034() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("platformPack_tile034", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Player1Texture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Player1Texture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Player2Texture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Player2Texture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SANDBLOCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SANDBLOCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STICK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STICK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE_AXE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE_AXE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE_AXE_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE_AXE_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE_PICKAXE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE_PICKAXE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE_PICKAXE_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE_PICKAXE_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE_SHOVEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE_SHOVEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE_SHOVEL_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE_SHOVEL_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE_SWORD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE_SWORD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STONE_SWORD_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STONE_SWORD_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stone1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stone1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vbnet_edition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vbnet_edition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water_still() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water_still", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOOD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOOD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOODEN_AXE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOODEN_AXE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOODEN_AXE_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOODEN_AXE_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOODEN_PICKAXE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOODEN_PICKAXE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOODEN_PICKAXE_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOODEN_PICKAXE_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOODEN_SHOVEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOODEN_SHOVEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOODEN_SHOVEL_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOODEN_SHOVEL_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOODEN_SWORD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOODEN_SWORD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WOODEN_SWORD_FLIPPED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WOODEN_SWORD_FLIPPED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
