Public Enum Material
    STONE 'DONE
    DIRT 'DONE
    GRASS_BLOCK
    COBBLESTONE 'DONE
    BEDROCK
    WOOD 'DONE
    PLANKS 'DONE
    WOODEN_PICKAXE 'DONE
    WOODEN_SWORD 'DONE
    WOODEN_AXE 'DONE
    WOODEN_SHOVEL 'DONE
    WORKBENCH ' crafting table
    STONE_PICKAXE 'DONE
    STONE_SWORD 'DONE
    STONE_AXE 'DONE
    STONE_SHOVEL 'DONE
    IRON_PICKAXE 'DONE
    IRON_SWORD 'DONE
    IRON_AXE 'DONE
    IRON_SHOVEL 'DONE
    DIAMOND_PICKAXE 'DONE
    DIAMOND_SWORD 'DONE
    DIAMOND_AXE 'DONE
    DIAMOND_SHOVEL 'DONE
    IRON 'DONE
    GOLD 'DONE
    STICK 'DONE
    DIAMOND 'DONE
    OBSIDIAN 'DONE
    SAND 'DONE
    GLASS 'DONE
    FURNACE 'DONE :D
    COAL '
End Enum
