
namespace NCore
{
    public enum EnumBlockType
    {
        AIR,
        GRASS_BLOCK,
        SNOWY_GRASS_BLOCK,
        DIRT,
        STONE,
        BEDROCK,
        COBBLESTONE,
        WATER,
        WOOD,
        PLANKS,
        LEAVES,
        COAL_ORE,
        IRON_ORE,
        IRON_BLOCK,
        GOLD_ORE,
        GOLD_BLOCK,
        DIAMOND_ORE,
        DIAMOND_BLOCK,
        OBSIDIAN,
        SAND,
        GLASS,
        FURNACE,
        SAPLING,
        TNT,
        LAVA,
        CHEST,
        END_STONE,
        FIRE,
        NETCRAFT_BLOCK,
        SNOWY_NETCRAFT_BLOCK,
        SEEDS,
        WHEAT,
        RED_FLOWER,
        YELLOW_FLOWER
    }
}